### ISSUE TITLE
Interoperability with Avatar Privacy

### ISSUE THREAD

**Issue by mundschenk-at** [allendav/profile-picture-privacy-controls#2]
Hi @allendav! 

You might want to check my [Avatar Privacy plugin](https://github.com/mundschenk-at/avatar-privacy) (also [in the WordPress repository](https://wordpress.org/plugins/avatar-privacy/)) for some ideas (and I'd welcome any suggestions you have for my plugin as well). 

It probably does more than your plugin and that might be too much for some folks, so I think there's a usecase for much leaner plugin (although I try to keep it tight). Still, it would be best if the common functionality of both plugins would work with each other's data (i.e. common user meta keys/data format) to minimize the plugin lock-in effect.

**Comment by allendav** [comment]
Hi @mundschenk-at  !

I took a look and it looks like I'd be interested in the GRAVATAR_USE_META_KEY user meta key https://github.com/mundschenk-at/avatar-privacy/blob/3e5b2faa08c2cf34fb5ed843662e05f214be6c06/includes/avatar-privacy/class-core.php#L64 

But... that key seems kinda generic? I worry about collision with other users of user meta, especially if/when core adds this as a user setting.  (That's one of the reasons I did the ppp_ prefix on mine - e.g. https://github.com/allendav/profile-picture-privacy-controls/blob/master/profile-picture-privacy-controls.php#L69 )

So, thank you very much for the suggestion, but I think I will decline. Cheers!

**Comment by mundschenk-at** [comment]
I have to admit I had hoped for a bit more of a discussion :( 

It certainly was not my intention posit the current state of Avatar Privacy's API as a given (`GRAVATAR_USE_META_KEY` is currently unprefixed for backwards compatibility with the original version of the plugin, but that can be changed in an upgrade routine). 

I don't think that having several plugins that do some of the same things in marginally incompatible ways is benefitting anyone. In that spirit, @allendav, I'd urge you to reconsider at least having a discussion on what it would take to arrive at a common framework. I think both plugins would benefit from that, even if, in the end, we could not agree on an API.

**Comment by allendav** [comment]
:) We can discuss more I suppose. I am trying to keep this plugin exceptionally simple. Did you have something in mind besides an agreed upon (prefixed) key and a value schema?

**Comment by mundschenk-at** [comment]
That's certainly the most important part. Due to user demand (I was suprised by that), I've also added a setting for users to allow anonymous gravatar use for their email (`ALLOW_ANONYMOUS_META_KEY`, which is already prefixed). Apparently quite a few people like to do their commenting on their own blog while logged-out. 

What would also be nice (but not strictly necessary):

- Conflict detection (i.e. a "Hey, you probably should not use two plugins doing the same thing!" warning). 
- Not deleting shared data on plugin deletion. (Instead, a `Delete data` button on the settings page could be provided - of course, this works best if a plugin has their own dedicated settings page, so it might not be an appropriate UX. There's been [a Core ticket for that](https://core.trac.wordpress.org/ticket/20578) for ages, but it is not going anywhere recently.)

**Comment by mundschenk-at** [comment]
Hi @allendav, how should we proceed from here?

**Comment by mundschenk-at** [comment]
So I guess this is not going to happen, is it? I'd still love to hear from you, @allendav. 

I'm currently in the process of adding unit tests to my plugin and refactoring the uninstallation logic. I could move the user meta to a prefixed one in the next version as well, if we can aggree on something.
